
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class romanos extends javax.swing.JFrame {
    
    private static void setmodel (DefaultListModel lista) {
            throw new UnsupportedOperationException("not supported yet."); //to change body of generation methods,
}
          String centena []={"C","CC","CCC","CD","D","DC","DCC","DCCC","CM"};
          String dezena  []={"X","XX","XXX","XL","L","LX","LXX","LXXX","XC"};
          String unidade  []={"I","II","III","IV","V","VI","VII","VIII","IX"};
        int num = 0, resto = 0;
  
   
    /**
     * Creates new form romanos
     */
    public romanos() {
        initComponents();
         setExtendedState(MAXIMIZED_BOTH);
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbromanos = new javax.swing.JTextArea();
        txnum = new javax.swing.JTextField();
        VTMENU = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("numero romano");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 280, 23));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("digite seu numero:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, 20));

        lbromanos.setColumns(20);
        lbromanos.setRows(5);
        jScrollPane1.setViewportView(lbromanos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 260, 170));

        txnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnumActionPerformed(evt);
            }
        });
        getContentPane().add(txnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 60, 30));

        VTMENU.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        VTMENU.setText("VOLTAR MENU");
        VTMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VTMENUActionPerformed(evt);
            }
        });
        getContentPane().add(VTMENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/romanoimg.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 680, 490));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 194, 260, 170));

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnumActionPerformed

        lbromanos.setText(" ");
        
        
         num = Integer.parseInt (txnum.getText())/ 100;
        resto = Integer.parseInt (txnum.getText()) % 100;

       if(num > 0)
       {
         lbromanos.setText( centena[num-1]);
       }
            num = resto  /10 ;
            resto = resto % 10 ;

          if (num > 0 )
       
           {lbromanos.setText(lbromanos.getText() + dezena [ num -1]);}
       
          if (resto > 0 )
       
           { lbromanos.setText(lbromanos.getText() + unidade [ resto -1]);}
       
          txnum.setText("");
    }//GEN-LAST:event_txnumActionPerformed

    private void VTMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VTMENUActionPerformed
        // TODO add your handling code here:
         menu telas = new menu ();
                telas.setVisible(true);
                
                this.dispose();
    }//GEN-LAST:event_VTMENUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(romanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(romanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(romanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(romanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new romanos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VTMENU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea lbromanos;
    private javax.swing.JTextField txnum;
    // End of variables declaration//GEN-END:variables
}
