
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class tabuada extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public tabuada() {
        initComponents();
         setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nmr = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ltTabuada = new javax.swing.JList<>();
        vtmenu = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 123, 127));
        setMinimumSize(new java.awt.Dimension(490, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        menu.setForeground(new java.awt.Color(160, 0, 0));
        menu.setText("TABUADA");
        menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 220, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("NUMERO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));
        getContentPane().add(nmr, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 70, 30));

        calcular.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        calcular.setText("CALCULAR");
        calcular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcularMouseClicked(evt);
            }
        });
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        getContentPane().add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        ltTabuada.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(ltTabuada);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 220, 250));

        vtmenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vtmenu.setText("VOLTAR MENU");
        vtmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtmenuActionPerformed(evt);
            }
        });
        getContentPane().add(vtmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
         
    }//GEN-LAST:event_calcularActionPerformed

    private void calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularMouseClicked

        DefaultListModel lista = new DefaultListModel();
        lista.clear();
        int resultado = 0;
        
        lista.addElement(" ");
        
        for (int x = 1; x < 11; x++)
        { 
            resultado = x * Integer.parseInt(nmr.getText());
            lista.addElement("         " + nmr.getText() + " x " + String.valueOf(x) + " = " + String.valueOf (resultado));
        }
                ltTabuada.setModel(lista);
       
    }//GEN-LAST:event_calcularMouseClicked

    private void vtmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtmenuActionPerformed
        // TODO add your handling code here:
        
         menu telas = new menu ();
                telas.setVisible(true);
                
                this.dispose();
    }//GEN-LAST:event_vtmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabuada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> ltTabuada;
    private javax.swing.JLabel menu;
    private javax.swing.JTextField nmr;
    private javax.swing.JButton vtmenu;
    // End of variables declaration//GEN-END:variables
}
